### ISSUE TITLE
期望可以自定义 popup 的宽高

### ISSUE THREAD

**Issue by liuxy0551** [JackWang032/doraemon-proxy-tool#2]
![image](https://github.com/JackWang032/doraemon-proxy-tool/assets/34759874/1bdd3fd9-f702-4a01-bacd-30871dcf68a1)
是否可以考虑再加两个输入框自行输入宽高

**Comment by JackWang032** [comment]
关联tag [v1.1.1](https://github.com/JackWang032/doraemon-proxy-tool/releases/tag/v1.1.1)
